version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=kn
      - RABBITMQ_DEFAULT_USER=kn
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"


  rabbitmq-publisher:
    image: rabbitmq-publisher  #HINT: to build this docker image, use the Dockerfile which exists in the following folder /docker/rabbitmq-publisher/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      PUBLISH_FREQUENCY: 5

  # Run the backend as docker here
  #backend:
  #.......
  backend:
    restart: always
    build: .
    container_name: container-shipment
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
